package paneldegestion;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.Login;

/**
 *
 * @author tonny
 */
public class PanelDeGestion extends javax.swing.JFrame {
    
    public static String TituloEntidad;
    public static String TipoDeEntidad;
    public static String CampoUnique;
    public static String Ruta2 = "D:\\Estructura de datos 3\\registros\\datos.txt";

    /**
     * Creates new form PanelDeGestion
     */
    public PanelDeGestion() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Panel De Gestion Principal");
        jComboBox1.setSelectedIndex(0);  // Establece el JComboBox en su primer elemento
        Botones.add(BotonSi);
        Botones.add(BotonNo);
        TextArea.setEditable(false);
        
        // En el siguiente try/catch tomamos los registros guardados y los exponemos en el TextArea
        FileReader leer;
        try {
            leer = new FileReader(Ruta2);
            BufferedReader br = new BufferedReader(leer);
            StringBuilder contenido = new StringBuilder(); // Usamos un StringBuilder para concatenar líneas

            String linea;
            try {
                while ((linea = br.readLine()) != null) {
                    contenido.append(linea).append("\n"); // Agregar cada línea al StringBuilder con un salto de línea   
                }
                // Mostrar el contenido en el TextArea
                    TextArea.setText(contenido.toString());
            } catch (IOException ex) {
                Logger.getLogger(PanelDeGestion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelDeGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BotonNo = new javax.swing.JRadioButton();
        BotonSi = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Guardar = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        TituloEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo De Entidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entidad Fuerte ( Independiente )", "Entidad Debil ( que depende de otra )" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, -1));

        BotonNo.setForeground(new java.awt.Color(255, 255, 255));
        BotonNo.setText("No");
        jPanel1.add(BotonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        BotonSi.setForeground(new java.awt.Color(255, 255, 255));
        BotonSi.setText("Si");
        jPanel1.add(BotonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contiene Campo Unique:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 20));

        TextArea.setBackground(new java.awt.Color(255, 255, 255));
        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 286, 690, 190));

        Guardar.setBackground(new java.awt.Color(51, 204, 0));
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons-guardar.gif"))); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, 40));

        CerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-llave.png"))); // NOI18N
        CerrarSesion.setText("CERRAR SESION");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, 40));

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-error.png"))); // NOI18N
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 100, 40));

        TituloEntrada.setBackground(new java.awt.Color(255, 255, 255));
        TituloEntrada.setForeground(new java.awt.Color(0, 0, 0));
        TituloEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(TituloEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo De La Entidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-panel.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 810, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloEntradaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        JOptionPane.showMessageDialog(null, "Usted Cerro Sesion", "Cierre de sesion", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    
    private static int idRegistro = 1;
    
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String linea;
        TituloEntidad = TituloEntrada.getText();
        TipoDeEntidad = (String)jComboBox1.getSelectedItem();
        
        if (TituloEntidad.isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Campo faltante", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            linea = "ID: "+idRegistro+", Titulo De La Entidad: "+TituloEntidad;
            linea += ", Tipo De Entidad: "+TipoDeEntidad;
        }
        if(BotonSi.isSelected()){
            linea += " ,Tiene Campo Unique: Si";
        }else if(BotonNo.isSelected()){
            linea += " ,Tiene Campo Unique: No";
        }else{
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Campo faltante", JOptionPane.ERROR_MESSAGE);
            return;
        }
               
        
        try (FileWriter writer = new FileWriter(Ruta2, true)) {
                writer.write(linea + "\n");
                JOptionPane.showMessageDialog(null, "Se guardo la entidad con exito!", "Guardado de entidad", JOptionPane.INFORMATION_MESSAGE);
                idRegistro++;
        } catch (IOException ex) {
                        ex.printStackTrace();
        }finally{
            FileReader leer;
            try {
                leer = new FileReader(Ruta2);
                BufferedReader br = new BufferedReader(leer);
                StringBuilder contenido = new StringBuilder(); // Usamos un StringBuilder para concatenar líneas

                try {
                    while ((linea = br.readLine()) != null) {
                        contenido.append(linea).append("\n"); // Agregar cada línea al StringBuilder con un salto de línea   
                    }
                    // Mostrar el contenido en el TextArea
                    TextArea.setText(contenido.toString());
                } catch (IOException ex) {
                    Logger.getLogger(PanelDeGestion.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                    Logger.getLogger(PanelDeGestion.class.getName()).log(Level.SEVERE, null, ex);
            }
            TituloEntrada.setText(""); // Pone en blanco la casilla de tutilo de la entidad despues de guardar un registro
        }
    }//GEN-LAST:event_GuardarActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeGestion().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonNo;
    private javax.swing.JRadioButton BotonSi;
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TituloEntrada;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
